### ISSUE TITLE
Imports from "kaitai.io" library not working

### ISSUE THREAD

**Issue by kudlav** [kaitai-io/kaitai_struct_webide#109]
I followed Katai [documentation](http://doc.kaitai.io/user_guide.html#_importing_types_from_other_files) and importing from preloaded library doesn't work.

 I have this simple ksy file:
```yaml
meta:
  id: foo
  imports:
    - /formats/network/ipv4_packet
seq:
  - id: dst_mac
    size: 6
  - id: src_mac
    size: 6
  - id: ether_type
    type: u2be
  - id: body
    type: ipv4_packet
```

This cause following errror (quite useless for user):
Parse error (TypeError): null has no properties
```
Call stack: [7]</Parser</Parser.prototype.cleanup@https://ide.kaitai.io/lib/_npm/yamljs/yaml.js:1220:9
[7]</Parser</Parser.prototype.parse@https://ide.kaitai.io/lib/_npm/yamljs/yaml.js:754:23
[11]</Yaml</Yaml.parse@https://ide.kaitai.io/lib/_npm/yamljs/yaml.js:1817:25
importYaml@https://ide.kaitai.io/js/v1/KaitaiServices.js:49:33
 TypeError: null has no properties
```
