### ISSUE TITLE
Move sample files out of this repo

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_webide#126]
I guess the way we store sample files doesn't scale well.

1. git is not very suitable for storing binary files.
2. binary files will bloat this repo and application.

Requirements for the solution:

* should not bloat the WebIDE repo
* the files should be loaded lazily
* should allow hosting actual files in the repos other than one single blessed repo
* should not require lot of maintaince from our side

Proposal:
1. store binary files in separate repos. If possible, not in our repos.
2. create a YAML file with an array, easch item of which list sources, like this:

```yaml
- uri: <direct uri to file sample. Must be available using CORS. Must be Wayback Machined before the addition>
- github: <a name of a GitHub repo>
  d-rx: <a regular expression dir path must satisfy>
  n-rx: <a regular expression file name (without rest of path) must satisfy>
```
3. CI script combines the sources, generating a file like this:
```yaml
- uri: <direct uri>
- uri: <direct uri>
  name: <used to resolve naming conflicts>
```

4. This list is used by the WebIDE to fetch the files. The WebIDE can even use the info from `*.ksy`s' `file-extension` to suggest the samples to a user.
