### ISSUE TITLE
Non-descriptive error messages

### ISSUE THREAD

**Issue by EntnyJill** [kaitai-io/kaitai_struct_webide#136]
We can see non-descriptive error message when some parse error occurs.
For example, for sequence of bytes 
`00 01 02 03 04 05 06 07 08 09 10 ...`
and ksy template
```
meta:
  id: test_template
  endian: be
seq:
  - id: fields
    type: u1
    repeat: expr
    repeat-expr: 5
  - id: delimiter
    contents:
      - 0xEE
```
we get error message:
```
Parse error: undefined
Call stack: undefined ValidationNotEqualError: not equal, expected [238], but got [5]
```
It would be better to get position of error, hexadecimal representations of expected and actual values, intermediate parsing results in object tree.
