### ISSUE TITLE
`-webide-representation` key not working for imported types

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct_webide#144]
I define two KSY files in WebIDE:
```yaml
meta:
  id: int
  endian: be
  encoding: ASCII
types:
  int:
    -webide-representation: "{value:dec}"
    seq:
      - id: raw
        type: str
        size-eos: true
    instances:
      value:
        value: raw.to_i
  hex:
    -webide-representation: "{value:dec}"
    seq:
      - id: raw
        type: str
        size-eos: true
    instances:
      value:
        value: raw.to_i(16)
```

```yaml
meta:
  id: imports
  imports:
    - int
seq:
  - id: field1
    type: int
    size: 2
  - id: field2
    type: int::hex
    size: 2
```
However, `-webide-representation` key not taken into account in the results:
![Kaitai Web IDE](https://user-images.githubusercontent.com/450131/187871043-7f65554d-2307-41cb-adc2-70fe66dd3fd8.png)
