### ISSUE TITLE
Parse error (TypeError): ksyType.instancesByJsName is undefined

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct_webide#145]
I have the following KEY in my local storage in WebIDE:
```yaml
meta:
  id: int
  encoding: ASCII
types:
  int:
    -webide-representation: "{value:dec}"
    seq:
      - id: raw
        type: str
        size-eos: true
    instances:
      value:
        value: raw.to_i
  hex:
    -webide-representation: "{value:dec}"
    seq:
      - id: raw
        type: str
        size-eos: true
    instances:
      value:
        value: raw.to_i(16)
```
When I double-click it the following error is thrown to the **Errors** pane:
> Parse error (TypeError): ksyType.instancesByJsName is undefined
> Call stack: 

This is not happened when I double-click any other KSY, for example, default `zip.ksy` from the gallery. This happens both on a devel and a stable WebIDE
