### ISSUE TITLE
"unable to find enum member" when using binary notation

### ISSUE THREAD

**Issue by bersbersbers** [kaitai-io/kaitai_struct_webide#150]
This throws an error:

```yaml
meta:
  id: foo
seq:
  - id: first_bit
    type: b1
    enum: my_enum
  - id: other_bits
    type:
      switch-on: first_bit
      cases:
        my_enum::x: b7
        my_enum::y: b15
enums:
  my_enum:
    0b0: x
    0b1: y
```

This works:

```yaml
meta:
  id: foo
seq:
  - id: first_bit
    type: b1
    enum: my_enum
  - id: other_bits
    type:
      switch-on: first_bit
      cases:
        my_enum::x: b7
        my_enum::y: b15
enums:
  my_enum:
    0: x
    1: y
```
