### ISSUE TITLE
Inheritance of conditions in csharp...

### ISSUE THREAD

**Issue by xavrr** [kaitai-io/kaitai_struct_webide#16]
Hi all, I'm not sure it's an issue or expected behaviour but the fact is that I didn't have this issue in the web ide or vsc so I wanted to share with you:

I have this kind os sequence in my ksy: 

    - id : value1
      type : u1
      if : header.value1bit == true
    - id : value2
      type : u4
      if : value1 == 0 

when evaluating value1 == 0 the csharp code wont check that it exists in the curent parsing context (only if header.value1bit == true) and would then evaluate value1==0 as true and the parsing is crashing.

I had to change it to:

      - id : value2
         type : u4
         if :  header.value1bit == true and value1 == 0 

I have the feeling that as we are referencing "value1" in the second expression, it should implicitly check that "value1" exists, kind of inherit that from the first expression...

**Comment by GreyCat** [comment]
This really has nothing to do with IDE specifically.

There are 2 problems you're describing here:

1. Invalid parsing due to `value1` having default value of 0, even if it wasn't really read due to failing condition.

It's a known problem with current C# implementation — it uses non-nullable types for primitive types like integers in any case, so you can't have "undefined" or "null" in an attribute that failed the condition to read it. [CI](http://kaitai.io/ci) shows that C# implementation fails "IfInstances" and "IfValues" tests.

Unfortunately, I'm not proficient enought in C# to fix it, may be we could ping @LogicAndTrick for that.

2. "implicitly check that "value1" exists". I don't quite understand how we could do that. To illustrate the problem, let's make it slightly more complex:

```yaml
seq:
  - id: value0
    type: u1
  - id: value1
    type: complex_type
    if: value0 == 1
  - id: value2
    type: u4
    if: value1.foo == 42
    # obviously, if "value1" is null due to "value != 1",
    # this will fail with NullReferenceException
types:
  seq:
    - id: foo
      type: u4
```

The problem here is that regular `.` operator translated to C#'s regular `.` operator does exactly what it does in C#. Some languages (like C# and Ruby) provide a more "relaxed" version of `.` operator, that incapsulates all that null pre-checks. If I'm not mistaken, that would work flawlessly, if we've compiled that into `value1&.foo == 42` in Ruby and `Value1?.Foo == 42` in C#. However, not all languages support that natively.
