### ISSUE TITLE
Silent error with no feedback

### ISSUE THREAD

**Issue by mckeed** [kaitai-io/kaitai_struct_webide#182]
I hit a syntax error that kaitai-struct-compiler doesn't handle well. Here's a minimal example:

```yaml
meta:
  id: test
  file-extension: test
seq:
  - id: test
    size: 0
instances:
  str:
    value: test.to_s() # illegal
```

The problem is the web IDE does not show an error message for this, so it's not obvious at first that something is wrong. If you already had a successful parse in the window, it looks like it's still working until you notice that nothing is updating any more. Very frustrating.

The js console shows

```
[Error] scala.scalajs.runtime.UndefinedBehaviorError: An undefined behavior was detected: undefined is not an instance of io.kaitai.struct.exprlang.Ast$expr
```

from raven.js. I can share a longer stack trace if that'd be helpful.
