### ISSUE TITLE
YAML parser doesn't recognize flow-style multi-line strings

### ISSUE THREAD

**Issue by natronium** [kaitai-io/kaitai_struct_webide#27]
This is valid YAML/KSY that contains a flow-folded string<sup>[[1]](http://yaml.org/spec/1.2/spec.html#id2779740)[[2]](http://yaml.org/spec/1.2/spec.html#id2779740)[[3]](http://yaml.org/spec/1.2/spec.html#id2779740)</sup>. 
```yaml
meta:
  id: example
  file-extension: example
seq:
  - id: stringdemo
    size: 0
    doc: This is a flow-style
      multi-line string
```
But causes the web IDE's YAML parser to throw a `ParseException`:
```YAML parsing error:  <ParseException> Unable to parse. (line 8: '  multi-line string')```

Quoting the string (with `'` or `"`) causes the parser to throw this exception instead:
```YAML parsing error:  <ParseException> Malformed inline YAML string ('This is a flow-style). (line 7: 'doc: 'This is a flow-style ')```

1. [Flow folding from official spec](http://yaml.org/spec/1.2/spec.html#id2779740)
2. [Flow-style strings from official spec](http://yaml.org/spec/1.2/spec.html#id2786942)
3. [Some friendlier unofficial YAML docs](http://camel.readthedocs.io/en/latest/yamlref.html#scalars) (The list  in the second half of the 'Scalars' section in particular)
