### ISSUE TITLE
Visualize GUID/UUID in its canonical form

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_webide#55]
If we have 16 bytes that are supposed to be GUID/UUID, I propose to add some hint that would allow us to display it in [its canonical text form](https://en.wikipedia.org/wiki/Universally_unique_identifier#Format), i.e. stuff like `123e4567-e89b-12d3-a456-426655440000`.

Currently we need hacks like that to get some sort of approximation:

```yaml
types:
  uuid:
    seq:
      - id: p1
        type: u4
      - id: p2
        type: u2
      - id: p3
        type: u2
      - id: p4
        type: u2be
      - id: p5
        size: 6
    -webide-representation: "{p1}-{p2}-{p3}-{p4}-{p5}"
```

However, it's better if we could get rid of special UUID type just for display purposes and get WebIDE to represent any 16-byte raw byte array as UUID using something like

    -webide-representation: "{some_attribute:uuid}"

or something like that.
