### ISSUE TITLE
Error message not going away

### ISSUE THREAD

**Issue by DarkShadow44** [kaitai-io/kaitai_struct_webide#61]
Since a few days, the error message doesn't disappear when the problem is resolved. Before, the error window would clear, showing me that the error is gone. Now the error is still shown, making it harder to know when it's resolved.

**Comment by koczkatamas** [comment]
It goes away for me. could you show me a minimized example and change sequence when the error occurs?

Also could you check that you have the latest WebIDE (caching issues, etc) which is:
```
Kaitai WebIDE version: 0.1-SNAPSHOT-e68f5b9 (2018-02-07 18:40:21, license)
Kaitai compiler version: 0.8-SNAPSHOT337369088 (2018-02-05 01:36:23.722)
```

**Comment by julie-bsx** [comment]
This sounds like an issue I just spent an hour working on -- comments in a `.ksy` file aren't included in the line number in the error message. For example,

```
# Line 1
# Line 2
# Line 3
# Line 4
types:
  animal:
      doc: An animal species
    seq:
      - id: species
        type: s4
  plant:
    seq:
      - id: species
        type: s4
```

will, assuming I entered an appropriate example, report the line number of the last comment line. There are ways to swap things around so that the line number is seriously confusing, but that would require I work _*really, really, hard*_ on the example.

**Comment by DarkShadow44** [comment]
Thanks for the quick reply, It doesn't seem to have to do with comments in my case.
My script:
```
meta:
  id: ribbon
  endian: le

seq:
  - id: unknown1
    size: 50
  - id: len_commands
    type: u4
  - id: commands
    type: application_command
    repeat: expr
    repeat-expr: len_commands

types:
  application_command:
    seq:
      - id: command_id
        size: 10
```

The file I'm working on (inside a zip or I can't attach it):
[tabs1.zip](https://github.com/kaitai-io/kaitai_struct_webide/files/1721701/tabs1.zip)

Just use the script on the file, add some syntax error, undo it again and the error won't disappear.
It works when I remove the "id: commands" part, btw.
