### ISSUE TITLE
Invalid line number while parsing YAML if comments are used

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_webide#62]
Report: https://github.com/kaitai-io/kaitai_struct_webide/issues/61#issuecomment-365401658
Example:
```yaml
# Line 1
# Line 2
# Line 3
# Line 4
types:
  animal:
      doc: An animal species
    seq:
      - id: species
        type: s4
  plant:
    seq:
      - id: species
        type: s4
```
Shows error at line 4, while the error is at line 7.
