### ISSUE TITLE
Allow custom attributes in .ksy files

### ISSUE THREAD

**Issue by scallacs** [kaitai-io/kaitai_struct_webide#76]
It would be nice to allow custom attributes in the .ksy definition file.

We could prefix these attributes with `x-` like OpenAPI does.
```
meta:
  id: my_id
seq:
  - id: myfield
    type: u4
    x-custom: my custom value
```

This is usefull to easily add extra informations and develop extensions.

Currently IDE throws an error when a non expected attribute is found is .ksy file:

> io.kaitai.struct.format.YAMLParseException: /seq/0/x-custom: unknown key found, expected: consume, doc, doc-ref, eos-error, id, if, include, repeat,
