### ISSUE TITLE
Endian switching results in undefined parsing error

### ISSUE THREAD

**Issue by Brayconn** [kaitai-io/kaitai_struct_webide#77]
Attempting to use an endian switching pattern like this:
```YAML
meta:
  id: endianswitchdemo1
  endian:
    switch-on: endian
    cases:
      '[0x49, 0x49]': le
      '[0x4d, 0x4d]': be
seq:
  - id: endian
    size: 2
```
results in this error:
```
Parse error: undefined
Call stack: undefined TypeError: a is undefined
```
This only occurs in the web ide, and compiles fine otherwise
